title: Jackie Wung
description: Jackie Wung is a Softwate Engineer and Creative Consultant living in Los Angeles.
url: jackiewung.com
author: Jackie Wung
social:
  name: Jackie Wung
  links:
    - https://instagram.com/jacquelinewung
plugins:
  - jekyll-seo-tag
